site_name: Ranger Documentation
site_description: "Ranger is tactical AI infrastructure that helps with automation and orchestration for cyber range training, experimentation, and exercise."
site_author: "Ranger Team at CMU SEI"
copyright: >
  Copyright &copy; 2025 Carnegie Mellon University. All rights reserved.
extra_css:
  - assets/extra.css
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - toc.integrate
  logo: assets/ranger.png
  favicon: assets/ranger.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: green

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: khaki
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra:
  # analytics:
  #   provider: google
  #   property: G-QXR9QHNERH
  social:
    - icon: material/message-question
      link: https://github.com/cmu-sei/rangerai/issues/new?template=question.md
      name: Ask a Question
    - icon: fontawesome/solid/bug
      link: https://github.com/cmu-sei/rangerai/issues/new?template=bug_report.md
      name: Report a Problem
    - icon: material/lightbulb-on
      link: https://github.com/cmu-sei/rangerai/issues/new?template=feature_request.md
      name: Request a Feature
    - icon: fontawesome/regular/comments
      link: https://github.com/cmu-sei/rangerai/discussions
      name: SSVC Community Discussions
    - icon: fontawesome/brands/github
      link: https://github.com/cmu-sei/rangerai
      name: cmu-sei/GHOSTS on Github
    - icon: fontawesome/regular/envelope
      link: mailto:info@sei.cmu.edu?subject=ranger%20Feedback
      name: Email Ranger Team at CMU SEI
    - icon: fontawesome/solid/house
      link: https://www.sei.cmu.edu/
      name: Software Engineering Institute
nav:
  - Home: index.md
  - Quick Start: quickstart.md
  - Infrastructure:
      - infrastructure/index.md
      - Client Interface: infrastructure/user_interface.md
      - Ranger Core API: infrastructure/ranger_api.md
      - Workflows: infrastructure/workflows.md
      - MCP: infrastructure/mcp.md
      - RAG: infrastructure/rag.md
      - Data Storage: infrastructure/data_storage.md
      - AI Provider: infrastructure/ai_provider.md
  - Deployment:
      - Deployment: deployment/index.md
      - Configuration: deployment/configuration.md
      - Tuning: deployment/tuning.md
repo_url: "https://github.com/cmu-sei/ranger"
repo_name: "cmu-sei/ranger"
